### ISSUE TITLE
PHP code

### ISSUE THREAD

**Issue by nathggns** [leafo/lessphp#101]
This isn't really a issue, more of a suggestion. Because this whole class is written in php, wouldn't it be extremely easy to add support for use of php within a *.less file. For example:

``` css
@border-radius (@radius:8) {
border-radius: <?=@radius+"px"?>;
}

#div {
@border-radius(5);
}
```

could be rendered as:

``` css
#div {
border-radius: 5px;
}
```

This is a very simple example and doesn't even begin to show to power of support for this.
