### ISSUE TITLE
Namespace Mixins (#gradient > .horizontal) from twitter Bootstrap preboot not compiled

### ISSUE THREAD

**Issue by emkayy** [leafo/lessphp#131]
Hi there,

I'm using twitters Bootstrap (http://twitter.github.com/bootstrap/) and everything seems to work fine.
Just the parametric mixins #font and #gradient won't work. They are included in the preboot.less file and look like that (shortend version):

``` css
#font {
  .shorthand(@weight: normal, @size: 14px, @lineHeight: 20px) {
    font-size: @size;
    font-weight: @weight;
    line-height: @lineHeight;
  }
  .sans-serif(@weight: normal, @size: 14px, @lineHeight: 20px) {
    font-family: "Helvetica Neue", Helvetica, Arial, sans-serif;
    font-size: @size;
    font-weight: @weight;
    line-height: @lineHeight;
  }
}

#gradient {
  .horizontal (@startColor: #555, @endColor: #333) {
    background-color: @endColor;
    background-repeat: repeat-x;
    background-image: -khtml-gradient(linear, left top, right top, from(@startColor), to(@endColor)); // Konqueror
    background-image: -moz-linear-gradient(left, @startColor, @endColor); // FF 3.6+
    background-image: -ms-linear-gradient(left, @startColor, @endColor); // IE10
    background-image: -webkit-gradient(linear, left top, right top, color-stop(0%, @startColor), color-stop(100%, @endColor)); // Safari 4+, Chrome 2+
    background-image: -webkit-linear-gradient(left, @startColor, @endColor); // Safari 5.1+, Chrome 10+
    background-image: -o-linear-gradient(left, @startColor, @endColor); // Opera 11.10
    background-image: linear-gradient(left, @startColor, @endColor); // Le standard
  }
  .vertical (@startColor: #555, @endColor: #333) {
    background-color: @endColor;
    background-repeat: repeat-x;
    background-image: -khtml-gradient(linear, left top, left bottom, from(@startColor), to(@endColor)); // Konqueror
    background-image: -moz-linear-gradient(@startColor, @endColor); // FF 3.6+
    background-image: -ms-linear-gradient(@startColor, @endColor); // IE10
    background-image: -webkit-gradient(linear, left top, left bottom, color-stop(0%, @startColor), color-stop(100%, @endColor)); // Safari 4+, Chrome 2+
    background-image: -webkit-linear-gradient(@startColor, @endColor); // Safari 5.1+, Chrome 10+
    background-image: -o-linear-gradient(@startColor, @endColor); // Opera 11.10
    background-image: linear-gradient(@startColor, @endColor); // The standard
  }
}
```

There are no errors when compiling but the rules are included in the stylesheet like that:

``` css
#font .shorthand(@weight: normal, #font $size: 14px, #font $lineHeight: 20px) {
  font-size:;
  font-weight:;
  line-height:;
}
```

but not when I'm using them like that:

``` css
#gradient > .vertical(lighten(@blue, 20%), @blue);
#font > .shorthand(bold, 15px, 1.2);
```

I don't understand why though since this works on your example page (http://leafo.net/lessphp/#demo):

``` css
#bundle {
  .button (@color: #000) {
    border: 1px solid @color;
    background-color: grey;
  }
}
#header a {
  color: orange;
  #bundle > .button(#ccc);
}
```
