### ISSUE TITLE
@@var Does Not Work

### ISSUE THREAD

**Issue by phaygoweb** [leafo/lessphp#137]
The following throws an error while compiling, "failed at 'content; @@var'"

``` css
@intro: "I am Phaygo";
@var: 'intro';

elem {
   content: @@var;
}
```

---

Should return, 

``` css
elem {
   content: 'I am Phaygo';
}
```
