### ISSUE TITLE
Wrong inheritance on several classes in one time

### ISSUE THREAD

**Issue by tankist** [leafo/lessphp#142]
The following code works in less.js, but don't work in lessphp:

``` css
.foo {
    color: red;
    .bar {
        font-family: sans-serif;
    }
}

.foobar {
    .foo .bar;
}
```

Expected:

``` css
.foo { color:red; }
.foo .bar { font-family:sans-serif; }
.foobar { font-family:sans-serif; }
```

Also removing .bar from the .foobar inheritance works:

``` css
.foo {
    color: red;
    .bar {
        font-family: sans-serif;
    }
}

.foobar {
    .foo;
}
```

...but also is not as expected:

``` css
.foo { color:red; }
.foo .bar { font-family:sans-serif; }
.foobar { color:red; }
.foobar .bar { font-family:sans-serif; } 
```

Expected:

``` css
.foo { color:red; }
.foo .bar { font-family:sans-serif; }
.foobar { color:red; }
```
