### ISSUE TITLE
@media rule BREAKS when multiple, comma-separated media queries in a single at-rule

### ISSUE THREAD

**Issue by Hlight** [leafo/lessphp#149]
``` css
@media 
    screen and (min-width: 102.5em) and (max-width: 117.9375em),
    screen and (min-width: 150em) {
    body {
        font-size: (@font-size + 2)/16*1em;
    }
}
```

The above code, when compiled with LESSPHP 0.2.1 results in:

``` css
$media screen and (min-width: 102.5em) and (max-width: 117.9375em) body, 
screen and (min-width: 150em) body { font-size:1.1875em; }
```
