### ISSUE TITLE
regexp support

### ISSUE THREAD

**Issue by prkos** [leafo/lessphp#181]
Is using regexp supported? Something like 

``` css
h([1-3]{1}) { 
  font-size: 1em + (3-$1) * 0.5em;
}
```

that would give 

``` css
h1 { 
  font-size: 2em;
}
h2 {
  front-size: 1.5em;
}
h3 {
  font-size: 1em;
}
```

or 

``` css
#content (p, li) a {

}
```

that would give 

``` css
#content p a,
#content li a {

}
```

If not is there any other way to do it, variables, mixins, pattern matching?
