### ISSUE TITLE
semantic.gs nested .column(x,y)

### ISSUE THREAD

**Issue by scottsweb** [leafo/lessphp#183]
lessphp v0.3.1
semantic.gs v1.2

I am experiencing an issue with nested columns and semantic.gs. I have tested the same code using the less.js and it works as expected. With lessphp the nested columns are being calculated incorrectly when @total-width is set to a percentage. When @total-width is set to a pixel value it works as expected.

The HTML:

``` HTML
<div id="container">
    <div id="content">
        <div id="row">
            <div id="left">
                <p>Left</p>
            </div>
            <div id="right">
                <p>Right</p>
            </div>
        </div>
    </div>
    <div id="sidebar">
        <p>Sidebar</p>
    </div>
</div>
```

The Grid less/css:

``` CSS
// Specify the number of columns and set column and gutter widths
@columns: 16;
@column-width: 40;
@gutter-width: 20;

// Remove the definition below for a pixel-based layout
@total-width: 100%;
```

The layout less/css:

``` CSS

#container
    {
    margin: 0 auto;
    max-width: 960px;
    }

#content
    {
    background: red;
    .column(12);
    height: 200px;
    }

#row
    {
    height: 200px;
    background: blue;
    .row(12);
    }

#left
    {
    height: 200px;
    background: black;
    .column(4,12);
    }

#right
    {
    height: 200px;
    background: aqua;
    .column(8,12);
    }

#sidebar
    {
    height: 200px;
    background: red;
    .column(4);
    }
```

I have not yet been able to determine why this is happening. Using less.js the nested column #left has a width of 219px and the #sidebar has a width of 220px (as expected). Using lessphp the #left column appears to be about 100px smaller than the #sidebar and to compensate I am setting #left to a width of .column(5) - which is still about 10px too small.
