### ISSUE TITLE
Parse error with extended `border-radius`

### ISSUE THREAD

**Issue by 0b10011** [leafo/lessphp#196]
The following snippet is valid CSS, but is parsed incorrectly by lessphp (but correctly by `less.js`).

``` CSS
body {
    border-radius:0 15px 15px 15px / 0 50% 50% 50%;
    /* Using: border-radius: <border-radius>{1,4} [ / <border-radius>{1,4}]? */
}
```

This causes an exception to be thrown:

> lessc fatal error:
> parse error: divide by zero

_**Note:_\* Using `lessphp-0.3.2`*
