### ISSUE TITLE
Parse error with "-" without preceding "0" (left:-(1px))

### ISSUE THREAD

**Issue by 0b10011** [leafo/lessphp#197]
Both of these examples work correctly (become `-1px`) in `less.js`, but the first becomes `-(1px)` in lessphp. Wrapping the first example does _not_ change the outcome.

``` CSS
body {
    left:-(1px); /* Becomes "-(1px)" INCORRECT */
    left:0-(1px); /* Becomes "-1px" CORRECT */
}
```

_**Note:_\* Using `lessphp-0.3.2`*
