### ISSUE TITLE
Mixins not mixed between each other (or even get overwritten)

### ISSUE THREAD

**Issue by denis111** [leafo/lessphp#200]
Hi, i was trying to add some stuff into existing mixin by declaring a new one with the same name and it didn't work. It works fine with lessjs. Here's simple example:

``` css
#testmixin {
  .red() {
    color:#f00 !important;
  }
}

#testmixin {
  .green() {
    color:#0f0 !important;
  }
}

body{
  #testmixin > .green();
}
```

In 'body' red will work, green not. With lessjs both work fine.
