### ISSUE TITLE
rgbahex() with HEX color returns transparent color

### ISSUE THREAD

**Issue by Alexious-sh** [leafo/lessphp#201]
Sample code:

``` css
.gradient(@c_top,@c_bottom) {
    background: linear-gradient(top,  @c_top,  @c_bottom);
    @ie_top: rgbahex(@c_top);
    @ie_bottom: rgbahex(@c_bottom);
    filter: e("progid:DXImageTransform.Microsoft.gradient(startColorstr=@{ie_top}, endColorstr=@{ie_bottom})");
}

// This works OK
.gradient1 { .gradient(rgba(255,255,0,1),rgba(0,255,255,1)); }

// This does transparent background in IE. Resulting colors are #00FFFF00 and #0000FFFF
.gradient1 { .gradient(#FFFF00,#00FFFF); }
```

Yes, I can write two functions for each variant, or write very big universal variant with Guards(as I doing now), but IMHO returning zero opacity here is not correct.
