### ISSUE TITLE
Variable reassignment order differs from the official LESS parser on imports

### ISSUE THREAD

**Issue by johnbacon** [leafo/lessphp#224]
LessPHP does not assign imports in the same order that lessc does, leading to some confusion on my part. ("Why won't my links stop being blue!?")

Here is an example:
#### example.less

``` css
@import "variables.less"; /* contains: @linkColor: #08c; @baseLineHeight: 18px; */
@import "styles.less"; /* contains: body { line-height:@baseLineHeight; } a { color:@linkColor; } */

@linkColor: #b30108;
@baseLineHeight: 19px;
```
##### Official LESS output

``` css
body { line-height:19px; }
a { color:#b30108; }
```
##### lessphp output

``` css
body { line-height:18px; }
a { color:#0088cc; }
```
