### ISSUE TITLE
"isnumber" returns true on rgba colors

### ISSUE THREAD

**Issue by zookatron** [leafo/lessphp#235]
The function "lib_isnumber" on line 1504 of lessc.inc.php incorrectly returns that a color is a number. I discovered this bug when trying to run the code from the front page of the LESS website:

``` less
@base: #f938ab;
.box-shadow(@style, @c) when (iscolor(@c)) {
  box-shadow:         @style @c;
  -webkit-box-shadow: @style @c;
  -moz-box-shadow:    @style @c;
}
.box-shadow(@style, @alpha: 50%) when (isnumber(@alpha)) {
  .box-shadow(@style, rgba(0, 0, 0, @alpha));
}
.box { 
  color: saturate(@base, 5%);
  border-color: lighten(@base, 30%);
  div { .box-shadow(0 0 5px, 30%) }
}
```

My solution was to change lib_isnumber from:

``` php
function lib_isnumber($value) {
    return $this->toBool(is_numeric($value[1]));
}
```

to:

``` php
function lib_isnumber($value) {
    return $this->toBool($value[0]!="color" and is_numeric($value[1]));
}
```
