### ISSUE TITLE
No support for .mixin() !important

### ISSUE THREAD

**Issue by nyordanov** [leafo/lessphp#236]
I've noticed that the following compiles fine with less.js, but not with lessphp:

source:

``` scss
.test() {
    color: red;
    background: white;
}

span {
    .test() !important;
}
```

expected result:

``` css
span {
  color: red !important;
  background: white !important;
}
```

Currently I get a fatal error:

```
Fatal Error: parse error: failed at `.test() !important;` test.less on line 7
```
