### ISSUE TITLE
Incorrect parse .placeholder()

### ISSUE THREAD

**Issue by Yahasana** [leafo/lessphp#241]
when there is no param and embed in any parent. .placeholder() parse out as 

``` css
&:-moz-placeholder { color:#999999; }
&:-ms-input-placeholder { color:#999999; }
&::-webkit-input-placeholder { color:#999999; }
```
