### ISSUE TITLE
Support for reverse mixin

### ISSUE THREAD

**Issue by a5e** [leafo/lessphp#243]
Lessphp doesn't support the &&& syntax which allow reverse mixin like this :

``` css
// Less
.ux-element{
    color:red;
    // fix IE
    .ie8&&&{
        color:blue;
    }
}

// compiled css
.ux-element{
    color:red;
}
.ie8 .ux-element{
    color:blue;
}
```

I've found this syntax [here](http://alwaystwisted.com/post.php?s=2012-06-05-another-approach-to-mobile-first-css-whilst-supporting-internet-explorer)
