### ISSUE TITLE
mixin generate invalid css code.

### ISSUE THREAD

**Issue by leeight** [leafo/lessphp#252]
``` less
.foo() {
    border: 1px solid red;
}

.test {
    .foo();
    border: 1px solid green;
}
```

after run command `plessc a.less`, the expected result should be

``` css
.test {
  border:1px solid red;
  border:1px solid green;
}
```

but i got 

``` css
.test {
  border:1px solid green;
  border:1px solid red;
}
```
