### ISSUE TITLE
Mixins properties always overwrite other properties.

### ISSUE THREAD

**Issue by stefanozoffoli** [leafo/lessphp#256]
Hi,

here is an example:

``` css
.mixin(){
  background: transparent;
  border: 0;
}

.foo{
  .mixin();
  background: red;
  border: 1px solid black;
}
```

When I compile using less.js it creates me the correct .foo class:

``` css
.foo{
  background: red;
  border: 1px solid black;
}
```

But when I compile using lessphp it creates this .foo class:

``` css
.foo{
  background: red;
  border: 1px solid black;
  background: transparent;
  border: 0;
}
```

So I can't overwrite properties that are already defined in a mixin.
