### ISSUE TITLE
Redefining CSS class in other document has no effect

### ISSUE THREAD

**Issue by lmeurs** [leafo/lessphp#265]
If I have 3 .less files, say:

fileA.less

``` less
.just-a-class { background: red; }
```

fileB.less 

``` less
.just-a-class { background: blue; }
```

and main.less

``` less
@import "fileA";
@import "fileB";

div { .just-a-class; }
```

Now all DIV's have a red background, even though fileB.less has redefined the background color to blue.

Redefining in fileA.less or main.less is not a problem, ie.:

fileA.less

``` less
.just-a-class { background: red; }
.just-a-class { background: blue; }
```

or main.less

``` less
@import "fileA";
@import "fileB";

.just-a-class { background: blue; }
div { .just-a-class; }
```

In both latter cases the DIV's backgrounds are blue.
