### ISSUE TITLE
Problem overriding variable assignments

### ISSUE THREAD

**Issue by squarestar** [leafo/lessphp#285]
``` less
@colorA: #fff;
@colorB: #000;
.test1 {
    color: @colorA;
    color: @colorB;
}
```

The rules above become: 

``` css
.test1 {
  color: #fff;
  color: #000;
}
```

All good. However, if I add to test1 so the whole thing looks like this:

``` less
@colorA: #fff;
@colorB: #000;
.test1 {
    color: @colorA;
    color: @colorB;
}
@colorA:@colorB;
.test2 {
    color: @colorA;
    color: @colorB;
}
```

The result is this:

``` css
.test1 {
  color: #000;
  color: #000;
}
.test2 {
  color: #000;
  color: #000;
}
```

This worked differently and more intuitively in v3.2 (which I've just upgraded from). Is this a bug? If not, how do I override a variable in the global scope without changing all previous usages of that variable?
