### ISSUE TITLE
Variables inside nth-last-child() parentheses don't render

### ISSUE THREAD

**Issue by reynoldsalec** [leafo/lessphp#292]
The following code...

``` less

.menu-spacing (@items) when (@items > 1){
  /* x items */
  li:first-child:nth-last-child(@items){
    width: 100% / @items;    
  }
  li:first-child:nth-last-child(@items) ~ li {
    width: 100% / @items;
  }
}

ul{
  .menu-spacing(5);
}
```

...renders this when compiled with lessphp:

``` css
ul li:first-child:nth-last-child(@items) {
  width: 20%;
}
ul li:first-child:nth-last-child(@items) ~ li {
  width: 20%;
}
```

I'm assuming there's an issue with placing variables within parentheses. I've checked this on another Less compiler (http://www.dopefly.com/less-converter/less-converter.html) which correctly compiled the code, so I'm guessing this is a lessphp-specific problem.
