### ISSUE TITLE
:hover pseudo-class not properly generated

### ISSUE THREAD

**Issue by Regaddi** [leafo/lessphp#300]
when using :hover in e.g.

``` less
a {
    color: @white;
    :hover {
        color: @blue;
    }
}
```

lessphp generates:

``` css
a :hover {
    color: #049cdb;
}
```

which is not recognized as a proper pseudo-class.

Tested with Google Chrome 21.0.1180.89 and Firefox 15.0.
