### ISSUE TITLE
Expressions Are Not Being Parsed At All, or Cause Errors since 1.3.8

### ISSUE THREAD

**Issue by Korzun** [leafo/lessphp#301]
[Expressions](http://leafo.net/lessphp/docs/#expressions) are not being processed. It seems that operators are where the problem lies. I'm processing LESS files through cachedCompile.

<hr/>

**Example 1:**
_LESS_

``` less
    @test:10 * 10px;
    .test{ text-size:@test; }
```

_CSS_

``` css
     .test{ text-size:10*10px; }
```

<hr/>

**Example 2:**
_LESS_

``` less
    @test:10 / 10px;
    .test{ text-size:@test; }
```

_Stack trace:_

``` html
#0 /home/.../utilitylessc.inc.php(2053): lessc_parser->throwError()
#1 /home/.../utility/lessc.inc.php1575): lessc_parser->parse('@test:10 / 10px...')
#2 /home/.../utility/lessc.inc.php(1611): lessc->compile('@test:10 / 10px...', '/home/korzun/de...')
#3 /home/.../utility/lessc.inc.php(1683): lessc->compileFile(...')
#4 /home/.../lessc.inc.php(353): lessc->cachedCompile('...')
```

<hr/>

This is my first issue report. This seems like a stupefyingly simple bug. While there is a 99% chance that I'm missing something, I have got to start somewhere. Thanks in advance @leafo.
