### ISSUE TITLE
Throwing parser error at @props: ~`"@{arguments}".replace(/[\[\]]|\,\sX/g, '')`;

### ISSUE THREAD

**Issue by potasiyam** [leafo/lessphp#355]
I was making css files from less for a project. But got parser error in the less function.

``` css
.box-shadow(@shadowA, @shadowB:X, ...){
  // Multiple shadow solution from http://toekneestuck.com/blog/2012/05/15/less-css-arguments-variable/
 @props: ~`"@{arguments}".replace(/[\[\]]|\,\sX/g, '')`;
  -webkit-box-shadow: @props;
     -moz-box-shadow: @props;
          box-shadow: @props; 
}
```

error was exactly for this line-

``` less
 @props: ~`"@{arguments}".replace(/[\[\]]|\,\sX/g, '')`;
```

I solved it temporarily by commenting this feature.
