### ISSUE TITLE
Elipses + mixins not working

### ISSUE THREAD

**Issue by PipelineBaron** [leafo/lessphp#375]
The following less

``` css
.box-shadow(...) {
  box-shadow: @arguments;
  -webkit-box-shadow: @arguments;
  -moz-box-shadow: @arguments;
}
#header {
  .box-shadow(2, 2px, 2px, black);
}
```

produces the following css

``` css
#header {
  box-shadow: ;
  -webkit-box-shadow: ;
  -moz-box-shadow: ;
}
```
