### ISSUE TITLE
Format function (%) doesn't support uppercase placeholders

### ISSUE THREAD

**Issue by webberig** [leafo/lessphp#386]
It appears that the lessphp implementation of the format function doesn't support uppercase placeholders.

Here's an example:

```
@color: #333333;
@url: %("../img/sprite_icons_%D.svg", @color);
background-image: (@url);
```

The (expected) output using less.js:

```
background-image: "../img/sprite_icons_%23333333.svg";
```

The output using lessphp

```
background-image: "../img/sprite_icons_#333333.svg";
```

As you can see, there is no difference between %d and %D while the less documentation states the following:

> Use uppercase placeholders if you need to escape special characters into their utf-8 escape codes. The function escapes all special characters except ()'~!. Space is encoded as %20. Lowercase placeholders leave special characters as they are.

**Comment by Krinkle** [comment]
This works as expected in https://github.com/wikimedia/less.php, and matches upstream behavior of [lesscss.org/less-preview](https://lesscss.org/less-preview/):


```css
div {
  @color: #333333;
  --lower: %("../img/sprite_icons_%d.svg", @color);
  --upper: %("../img/sprite_icons_%D.svg", @color);
}
```
```
$ bin/lessc example.less 
```
```css
div {
  --lower: "../img/sprite_icons_#333333.svg";
  --upper: "../img/sprite_icons_%23333333.svg";
}
```
