### ISSUE TITLE
Compiling creates an unnecessary whitespace

### ISSUE THREAD

**Issue by basteyy** [leafo/lessphp#416]
With the latest version (from website) I tried to compile this:

``` css
#toolbar a{

    color: white;  

    :hover {
        color: red;
    }
}
```

The result ..

``` css
#toolbar a {
  color: white;
}
#toolbar a :hover {
  color: red;
}
```

is wrong (see http://leafo.net/lessphp/editor.html#%23toolbar%20a%7B%0A%0A%20%20%20%20color%3A%20white%3B%20%20%0A%0A%20%20%20%20%3Ahover%20%7B%0A%20%20%20%20%20%20%20%20color%3A%20red%3B%0A%20%20%20%20%7D%0A%7D)

So I think its a bug.
