### ISSUE TITLE
Conditional CSS Code

### ISSUE THREAD

**Issue by valllabh** [leafo/lessphp#417]
How about having something like conditional css code depending upon variable

``` css

@has_theme_support: true;

.awesome-class {
    width: 100px;
    height: 200px;
    margin: 0 auto;

    /* Adds theme support if @has_theme_support is 'true'; */
    if( @has_theme_support ){
        background: green;
        color: yellow;
    }
}
```
