### ISSUE TITLE
Mixin and class conflict

### ISSUE THREAD

**Issue by alex-pex** [leafo/lessphp#437]
Running the following code from Flat-UI fails to compile

``` css
.caret(@color: @base) {
  border-left-width: 6px;
  border-right-width: 6px;
  border-top-width: 8px;
  border-bottom-color: @color;
  border-style: solid;
  border-bottom-style: none;
  border-top-color: @color;
  .transition(.25s);
}

.caret {
  .caret();
  .transform(scale(1.001));
}
```

lessphp doesn't understand `.caret()`, but less compiler with nodeJS does
