### ISSUE TITLE
Incorect mixin compile, unable to set variable within mixin

### ISSUE THREAD

**Issue by jakubriedl** [leafo/lessphp#442]
There is a issue on setting variable in mixin.
I have this less code

``` less
@body-background-color: black;
@post-background-color: white;
@post-stacked-effect: "true";

.content-padding() {
    @content-padding: 20px;
}
.content-padding() when ( @body-background-color = @post-background-color ) and not (@post-stacked-effect = true) and not (@post-stacked-effect = "true"){
    @content-padding: 0px;
}
body {
    .content-padding();
    content: "@{post-stacked-effect}";
    padding: @content-padding;
    background-color: @body-background-color;
    .post {
        background-color: @post-background-color;
    }
    .some-math {
            margin: -@content-padding -@content-padding @content-padding;
    }
}
```

it should be compiled into this css

``` css
body {
  content: "true";
  padding: 20px;
  background-color: #000000;
}
body .post {
  background-color: #ffffff;
}
body .some-math {
  margin: -20px -20px 20px;
}
```

but it is badly compiled into this

``` css
body {
  content: "true";
  padding: ;
  background-color: black;
}
body .post {
  background-color: white;
}
body .some-math {
  margin: - - ;
}
```
