### ISSUE TITLE
Problem with multiple mixins with the same name

### ISSUE THREAD

**Issue by Texungo** [leafo/lessphp#465]
When I try to call with LESS PHP returns: 

``` PHP

Fatal Error:
====================
Failed to assign arg @line: failed at `.font(Arial);` line: 103

```

But with less.js, returns right:

``` CSS

.class0 {
  font-family: Arial;
}
.class1 {
  font-size: 12pt;
  line-height: 16pt;
}
.class2 {
  font-size: 12pt;
  line-height: 15px;
}
.class3 {
  font-size: 15pt;
  line-height: 12px;
  font-family: Arial;
}
.class4 {
  color: #000000;
  font-size: 15px;
  line-height: 20px;
}

.class5 {
  color: #0000ff;
  font-size: 50em;
  line-height: 10px;
}
.class6 {
  color: #ff0000;
  font-size: 10px;
  line-height: 12px;
  font-family: Arial;
}
.class7 {
  color: #ffff00;
  font-size: 20pt;
  line-height: 15px;
  font-family: Arial;
}


```

There is the code:

``` Less

/* font-family: @family; */
.font(@family) when not (isnumber(@family)) {
    font-family: @family;
}

/**
 * font-size: @size;
 * line-height: line-height calculado a partir do @size;
 */
.font(@size) when (isnumber(@size)){
    .f-size(@size);
}

/**
 * font-size: @size;
 * line-height: @line;
 */
.font(@size, @line) when (isnumber(@size)) and (isnumber(@line)){
    .f-size(@size, @line);
}

/**
 * color: @color;
 * font-size: @size;
 * line-height: line-height calculado a partir do @size;
 */
.font(@size, @color) when (isnumber(@size)) and (iscolor(@color)){
    color: @color;

    .f-size(@size);
}

/**
 * color: @color;
 * font-size: @size;
 * line-height: @line;
 */
.font(@size, @line, @color) when (isnumber(@size)) and (isnumber(@line)) and (iscolor(@color)) {
    color: @color;

    .f-size(@size, @line);
}


/**
 * font-size: @size;
 * line-height: line-height calculado a partir do @size;
 * font-family: @family;
 */
.font(@size, @family) when (isnumber(@size)) and not (isnumber(@family)) and not (iscolor(@family)){
    .f-size(@size);
    font-family: @family;
}


/**
 * font-size: @size;
 * line-height: @line;
 * font-family: @family;
 */
.font(@size, @line, @family) when (isnumber(@size)) and (isnumber(@line)) and not(iscolor(@family)) {
    .f-size(@size, @line);
    font-family: @family;
}

/**
 * color: @color;
 * font-size: @size;
 * line-height: line-height calculado a partir do @size;
 * font-family: @family;
 */
.font(@size, @family, @color) when (isnumber(@size)) and not (isnumber(@family)) and (iscolor(@color)){
    color: @color;

    .f-size(@size);
    font-family: @family;
}

/**
 * color: @color; 
 * font-size: @size;
 * line-height: @line;
 * font-family: @family;
 */
.font(@size, @line, @family, @color) {
    color: @color;

    .f-size(@size, @line);
    font-family: @family;
}

.f-size (@val) {
    font-size: @val * 1px;
    line-height: (round((@val / 1.618) * 2.5) - 3) * 1px;
}

.f-size(@val, @line) {
    font-size: @val * 1px;
    line-height: @line * 1px;
}

.class0 {
    .font(Arial);
}

.class1 {
    .font(12pt);
}

.class2 {
  .font(12pt, 15px);
}

.class3 {
  .font(15pt, 12px, Arial)
}

.class4 {
  .font(15px, black);
}

.class5 {
  .font(50em, 10px, blue);
}

.class6 {
  .font(10px, Arial, red);
}

.class7 {
  .font(20pt, 15px, Arial, yellow);
}


```
