### ISSUE TITLE
Undefined variables should result in an error

### ISSUE THREAD

**Issue by jgonera** [leafo/lessphp#475]
Current behavior makes it more difficult to find bugs in LESS files and produces incorrect CSS files. Create the following `test.less` file:

``` css
.test-mixin() {
  color: @nothing;
}

.test {
  .test-mixin();
}
```

Running `plessc test.less` (latest master) results in:

```
.test {
  color: ;
}
```

Expected result (`lessc test.less`, LESS 1.4.2):

```
SyntaxError: variable @nothing is undefined in /home/jgonera/lessphp/test.less on line 6, column 3:
5 .test {
6   .test-mixin();
7 }
```
