### ISSUE TITLE
Recursive mixin in a nested rule

### ISSUE THREAD

**Issue by Romashka** [leafo/lessphp#482]
``` less
.func (@color) {
  .recursive (@index) when (@index > 0) {
    .div {
      color: @color;
    }
    .recursive(@index - 1);
  }
  .recursive (0) {}

  .wrap {
    .recursive (3);
  }
}

.func(red);
.func(blue);
```

expected:

``` css
.wrap .div { color:red; }
.wrap .div { color:red; }
.wrap .div { color:red; }
.wrap .div { color:blue; }
.wrap .div { color:blue; }
.wrap .div { color:blue; }
```

actual:

``` css
.wrap .div { color:red; }
.wrap .div { color:red; }
.wrap .div { color:red; }
.wrap .div { color:blue; }
.wrap .div { color:red; }
.wrap .div { color:red; }
```

but this snippet(without .wrap) works as expected:

``` less
.func (@color) {
  .recursive (@index) when (@index > 0) {
    .div {
      color: @color;
    }
    .recursive(@index - 1);
  }
  .recursive (0) {}

  .recursive (3);
}

.func(red);
.func(blue);
```
