### ISSUE TITLE
Variables not visible outside mixin

### ISSUE THREAD

**Issue by Roope** [leafo/lessphp#517]
Hello! Didn't find any mention about this earlier so here we go.

With less.js (any version) you can do:

``` css
.my-vars() {
  @foo: 10px;
}

.margin() {
  .my-vars();
  margin: @foo;
}

div {
  .margin();
}
```

and it compiles to:

``` css
div {
  margin: 10px;
}
```

but with lessc var is not visible. It throws:

```
fatal error: variable @foo is undefined: failed at `margin: @foo;` line: 8
```
