### ISSUE TITLE
Use $less->setVariables to create media query variable

### ISSUE THREAD

**Issue by gerbenvandijk** [leafo/lessphp#527]
for a project of mine I am looking for a way to use the $less->setVariables() function to set a media query in a variable like this:

``` php
$less->setVariables(array(

    'mq' => 'only screen and (min-width : 320px) and (max-width : 480px)'

));         
```

and then use it like this:

``` css
@media @mq {

    html {

        background-color: yellow;

    }

}
```

But the setVariables() function first parses the variables for valid CSS; and somehow the variable breaks like this:

``` css
@media only screen and{

    html {

        background-color: yellow;

    }

}
```

Is there a way to make this work? 

A bit of background info:
I am using a PHP function to generate an array with mediaqueries. I can then use the information in this array to do the following:
- use the media queries in my LESS (at least that's what I'm trying)
- use the media queries in JS
- use the dimensions of the media queries to set new image sizes for Wordpress
- etc
