### ISSUE TITLE
variable override

### ISSUE THREAD

**Issue by Evanion** [leafo/lessphp#558]
It seems that the current implementation doesn't support variable override across files.
If a variable is set, it's not possible to change it in a parent file.

Works:

``` less
@var1: 40px;
.class1 {
    height: @var1; }
@var1: 60px;
```

Doesn't work:
(file1.less):

``` less
@var1: 40px;
.class1 {
    height: @var1; }
```

 (file2.less):

``` less
@import "file1.less";
@var1: 60px;
```

I have been working with the Warp 7 framework for the past year, and having this possibility, makes it possible to define a default value, and then override it. Some frameworks (like uikit) rely on this feature.
