### ISSUE TITLE
parse error: failed at `&:extend(.clearfix all);

### ISSUE THREAD

**Issue by Pavel910** [leafo/lessphp#580]
I'm trying to compile Bootstrap less files, and the compiler throws this exception:

`parse error: failed at `&:extend(.clearfix all);`

The LESS code looks like the following:

``` less
.container-fixed() {
  margin-right: auto;
  margin-left: auto;
  padding-left:  (@grid-gutter-width / 2);
  padding-right: (@grid-gutter-width / 2);
  &:extend(.clearfix all);
}
```

I'm using your compiler because it supports absolute paths in @import statement, so it would be great if you could fix this one. Thanks.
