### ISSUE TITLE
Doesn't compile variables in media queries' conditions

### ISSUE THREAD

**Issue by Zzortell** [leafo/lessphp#593]
On running of this code :
```less
@media_1 : 1600px;

@media (min-width: @media_1) {
 	header
	{
		background-color: white;
  }
}
```
The compiler throw : 
```
Fatal Error:
====================
parse error: failed at `@media_1 : 1600px;` line: 1
```
