### ISSUE TITLE
Passing Rulesets to Mixins

### ISSUE THREAD

**Issue by dlid** [leafo/lessphp#614]
Hi, i can't seem to be able to pass rulesets to mixins as described in http://lesscss.org/features/#detached-rulesets-feature

Is it not implemented, or is it implemented differently?

I've tried this with lessphp 0.4.0 and 0.5.0

```css
.desktop-example(@rules) {
 @media screen and (min-width: 1200) { 
  @rules(); 
 }
}

header {
 background-color: blue;
  .desktop-example({
   background-color: red;
  });
}
```
