### ISSUE TITLE
@supports CSS Feature Queries not working

### ISSUE THREAD

**Issue by meltajon** [leafo/lessphp#632]
When trying to use `@supports`, the output is nothing. For example:

```css
@supports (display: grid) {
     // code that will only run if CSS Grid is supported by the browser
    display: grid;
 }
```

The output is simply null.

I'm guessing it's trying to treat `@supports` as a variable instead of literally, like `@media`.
