### ISSUE TITLE
Parse error with CSS Grid Layout and named grid lines/areas

### ISSUE THREAD

**Issue by Celti** [leafo/lessphp#637]
When attempting to use [named grid lines](https://www.w3.org/TR/css-grid-1/#named-line) and areas in a LESS stylesheet I get a parse error from `lessphp`. `less.js` works just fine.
```
Fatal Error: parse error: failed at `grid-template-rows:` ../../lib/tpl/dokuwiki-template-grid/css/structure.less on line 12
```

```less
#dokuwiki__site {
    display: grid;
    box-sizing: border-box;
    width: 100vw;
    height: 100vh;
    grid-template-rows:
        [header] 2em
        [content] 1fr
        [footer] 2em;
    grid-template-columns:
        [left] minmax(auto, min-content)
        [center] auto
        [right] minmax(auto, min-content);
    grid-gap: 1px;
}
```
