### ISSUE TITLE
recursive mixin not working in nested rule

### ISSUE THREAD

**Issue by sebenik** [leafo/lessphp#644]
Input:

```less
.nested-class(4);

.nested-class(@n, @i: 1) when (@i =< @n) {
  .class {
    .nested-class(@n, (@i + 1));
    width: (@i * 100% / @n);
  }
}
```

Expected output:
```css
.class {
  width: 25%;
}
.class .class {
  width: 50%;
}
.class .class .class {
  width: 75%;
}
.class .class .class .class {
  width: 100%;
}
```

Wrong output of lessphp:
```css
.class {
  width: 16.666666666667%;
}
.class .class {
  width: 33.333333333333%;
}

```
